[project]
name = "clarity-security-templates"
authors = ["Timothy Chimbiv"]
description = "Modular security template for Clarity developers"
telemetry = false

[contracts.security-rules-trait]
path = "contracts/traits/security-rules-trait.clar"
clarity_version = 4
epoch = 3.3

[contracts.rules]
path = "contracts/wallet/rules.clar"
clarity_version = 4
epoch = 3.3

[contracts.wallet]
path = "contracts/wallet/wallet.clar"
clarity_version = 4
epoch = 3.3

[repl]
costs_version = 2
parser_version = 2